version: "3"
services:
  api:
    build:
      context: ..
      dockerfile: ./cmd/api/Dockerfile.debug
    platform: linux/{{platform}}
    entrypoint: ["./dlv", "--listen=:40000", "--headless=true", "--accept-multiclient", "--continue", "--api-version=2", "exec", "./api"]
    environment:
      - OTEL_SERVICE_NAME=tableland:api # this is just to the unknown_service from the metrics label
    env_file:
      - ${ENV_FILE}
    ports:
      - "127.0.0.1:8080:8080" 
      - "127.0.0.1:9090:9090"
      - "127.0.0.1:40000:40000"
    volumes:
      - ${PWD}/${ENVIROMENT}/api:/root/.tableland
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    volumes:
      - ${PWD}/observability/prometheus:/etc/prometheus
      - ${PWD}/${ENVIROMENT}/prometheus:/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    ports:
      - "127.0.0.1:9091:9090"
