apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-01
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: VALIDATOR_ALCHEMY_OPTIMISM_KOVAN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tableland-secret
                  key: validator-alchemy-optimism-kovan-api-key
            - name: VALIDATOR_ALCHEMY_ETHEREUM_GOERLI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tableland-secret
                  key: validator-alchemy-ethereum-goerli-api-key
            - name: VALIDATOR_ALCHEMY_POLYGON_MUMBAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tableland-secret
                  key: validator-alchemy-polygon-mumbai-api-key
            - name: VALIDATOR_OPTIMISM_KOVAN_SIGNER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: tableland-secret
                  key: validator-optimism-kovan-signer-private-key
            - name: VALIDATOR_ETHEREUM_GOERLI_SIGNER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: tableland-secret
                  key: validator-ethereum-goerli-signer-private-key
            - name: VALIDATOR_POLYGON_MUMBAI_SIGNER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: tableland-secret
                  key: validator-polygon-mumbai-signer-private-key
