linters-settings:
  misspell:
    locale: US

linters:
  enable:
    - revive
    - misspell
    - bodyclose
    - unconvert
    - goconst
    - goimports
    - unparam
    - whitespace
    - godot
    - lll
    - sqlclosecheck
    - gofumpt

issues:
  exclude-use-default: false

  exclude:
    - stutters
  
run:
  timeout: 30m

  skip-dirs:
    - "pkg/sqlstore/impl/system/internal/db"