{
 "title": "Validator",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Is everything ok?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "runtime_uptime_milliseconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "HealthBot - e2e check",
   "type": "stat",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sum by (chain_name) (tableland_healthbot_e2eprobe_last_check)",
     "legendFormat": "Last check {{chain_name}}"
    },
    {
     "expr": "time() - sum by (chain_name) (tableland_healthbot_e2eprobe_last_successful_check)",
     "legendFormat": "Last success {{chain_name}}"
    }
   ]
  },
  {
   "title": "Ethereum node API is healthy",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chain_id)(tableland_wallettracker_eth_client_unhealthy{service_name=\"tableland:api\"}) < BOOL 1",
     "legendFormat": "ChainID: {{chain_id}}"
    }
   ]
  },
  {
   "title": "Wallet balances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chain_id) (tableland_wallettracker_balance_wei{service_name=\"tableland:api\"})/1000000000",
     "legendFormat": "Chain ID {{chain_id}}"
    }
   ]
  },
  {
   "title": "Last backup",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - tableland_backup_last_execution"
    }
   ]
  },
  {
   "title": "Last Hash Calculation Elapsed Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tableland_eventprocessor_hash_calculation_elapsed_time / 1000",
     "legendFormat": "Chain ID: {{chain_id}}"
    }
   ]
  },
  {
   "title": "Events processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last detected block number",
   "type": "timeseries",
   "description": "Shows the last block number detected. It should always have a positive trend.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (chain_id) (tableland_eventfeed_height{service_name=\"tableland:api\"})",
     "legendFormat": "ChainID: {{chain_id}}"
    }
   ]
  },
  {
   "title": "Last processed block number",
   "type": "timeseries",
   "description": "Show the last successfully processed event height",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by (chain_id) (tableland_eventprocessor_last_processed_height{service_name=\"tableland:api\"})",
     "legendFormat": "ChainID: {{chain_id}}"
    }
   ]
  },
  {
   "title": "Detected Event Types per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "c/s" } },
   "targets": [
    {
     "expr": "sum by (chain_id, name) (rate(tableland_eventfeed_eventypes_count_total{service_name=\"tableland:api\"}[5m]))",
     "legendFormat": "ChainID: {{chain_id}} Event: {{name}}"
    }
   ]
  },
  {
   "title": "Processed Event Types per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (chaind_id, eventtype) (rate(tableland_eventprocessor_event_execution_count_total{service_name=\"tableland:api\"}[5m]))",
     "legendFormat": "{{chain_id}} {{eventtype}}"
    }
   ]
  },
  {
   "title": "EVM transaction processing latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(tableland_eventprocessor_txn_execution_latency_bucket{service_name=\"tableland:api\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block processing latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(tableland_eventprocessor_block_execution_latency_bucket{service_name=\"tableland:api\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Retry execution rounds",
   "type": "stat",
   "description": "How many times the current pending event to be processed was retried. This number should be in general zero. Maybe up to 3. If this number is high, something is wrong sine we're stuck at trying to process the event for some reason that should be fixed.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chain_id) (tableland_eventprocessor_execution_round{service_name=\"tableland:api\"})",
     "legendFormat": "ChainID {{chain_id}}"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "REST req/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_status_code) (rate(http_server_request_count_total{service_name=\"tableland:api\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REST 95-th latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service_name=\"tableland:api\"}[$__rate_interval])) by (http_status_code, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response bytes/s ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(http_server_response_content_length_total[$__rate_interval])",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  { "title": "Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Method Request/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (method) (\n  rate(tableland_gateway_call_latency_count{service_name=\"tableland:api\"}[$__rate_interval])\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Methods 95-tile latency",
   "type": "timeseries",
   "description": "The latency of 95% tile. Note that CreateTable is a long running request since requires sending a txn to Ethereum. The rest should have low-ish latencies.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tableland_gateway_call_latency_bucket{service_name=\"tableland:api\"}[$__rate_interval])) by (le, method))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SQL Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Event Feed Store Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (chainID, method) (\n  rate(tableland_eventfeed_store_call_count_total{service_name=\"tableland:api\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Feed Store Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tableland_eventfeed_store_latency_bucket{service_name=\"tableland:api\"}[5m])) by (le, chainID, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open connections",
   "type": "timeseries",
   "description": "Number of open connections.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by ( name, status) (db_sql_connection_open{database=\"main\"})",
     "legendFormat": "{{chain_id}}-{{name}}-{{status}}"
    }
   ]
  },
  {
   "title": "Overall SQL query 95-th latency",
   "type": "timeseries",
   "description": "Raw 95th tile latency of all executed queries in the database.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_sql_latency_milliseconds_bucket{database=\"main\"}[$__rate_interval])) by ( name, le))",
     "legendFormat": "{{chain_id}}-{{name}}"
    }
   ]
  },
  {
   "title": "CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage (runtime)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_inuse_bytes",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "#goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "process_runtime_go_goroutines", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "GC/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "gc/s" } },
   "targets": [
    {
     "expr": "rate(process_runtime_go_gc_count[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Live objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(process_runtime_go_mem_live_objects[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}