version: "3"
services:
  api:
    build:
      context: ..
      dockerfile: ./cmd/api/Dockerfile
    platform: linux/${PLATFORM}
    environment:
      - OTEL_SERVICE_NAME=tableland:api # this is just to the unknown_service from the metrics label
    env_file:
      - ${PWD}/${ENVIROMENT}/api/.env_validator
    ports:
      - "127.0.0.1:8080:8080" 
    volumes:
      - ${PWD}/${ENVIROMENT}/api:/root/.tableland
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped