{{- if .Values.rbac.create -}}
{{- $fullName := include "tableland.uname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ template "tableland.serviceAccount" . }}"
  annotations:
    {{- with .Values.rbac.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "tableland.labels" . | nindent 4 }}
{{- end -}}
