// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: schema.sql

package db

import (
	"context"
)

const getSchemaByTableName = `-- name: GetSchemaByTableName :one
SELECT sql FROM sqlite_master WHERE name=?1
`

func (q *Queries) GetSchemaByTableName(ctx context.Context, name string) (string, error) {
	row := q.queryRow(ctx, q.getSchemaByTableNameStmt, getSchemaByTableName, name)
	var sql string
	err := row.Scan(&sql)
	return sql, err
}
