// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: id.sql

package db

import (
	"context"
)

const getId = `-- name: GetId :one
SELECT id FROM system_id
`

func (q *Queries) GetId(ctx context.Context) (string, error) {
	row := q.queryRow(ctx, q.getIdStmt, getId)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertId = `-- name: InsertId :exec
INSERT INTO system_id (id) VALUES (?)
`

func (q *Queries) InsertId(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.insertIdStmt, insertId, id)
	return err
}
