// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: nonce.sql

package db

import (
	"context"
	"database/sql"
)

const deletePendingTxByHash = `-- name: DeletePendingTxByHash :exec
DELETE FROM system_pending_tx WHERE chain_id=?1 AND hash=?2
`

type DeletePendingTxByHashParams struct {
	ChainID int64
	Hash    string
}

func (q *Queries) DeletePendingTxByHash(ctx context.Context, arg DeletePendingTxByHashParams) error {
	_, err := q.exec(ctx, q.deletePendingTxByHashStmt, deletePendingTxByHash, arg.ChainID, arg.Hash)
	return err
}

const insertPendingTx = `-- name: InsertPendingTx :exec
INSERT INTO system_pending_tx (chain_id, address, hash, nonce) VALUES (?1, ?2, ?3, ?4)
`

type InsertPendingTxParams struct {
	ChainID int64
	Address string
	Hash    string
	Nonce   int64
}

func (q *Queries) InsertPendingTx(ctx context.Context, arg InsertPendingTxParams) error {
	_, err := q.exec(ctx, q.insertPendingTxStmt, insertPendingTx,
		arg.ChainID,
		arg.Address,
		arg.Hash,
		arg.Nonce,
	)
	return err
}

const listPendingTx = `-- name: ListPendingTx :many
SELECT chain_id, address, hash, nonce, bump_price_count, created_at, updated_at FROM system_pending_tx WHERE address = ?1 AND chain_id = ?2 order by nonce
`

type ListPendingTxParams struct {
	Address string
	ChainID int64
}

func (q *Queries) ListPendingTx(ctx context.Context, arg ListPendingTxParams) ([]SystemPendingTx, error) {
	rows, err := q.query(ctx, q.listPendingTxStmt, listPendingTx, arg.Address, arg.ChainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemPendingTx
	for rows.Next() {
		var i SystemPendingTx
		if err := rows.Scan(
			&i.ChainID,
			&i.Address,
			&i.Hash,
			&i.Nonce,
			&i.BumpPriceCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replacePendingTxByHash = `-- name: ReplacePendingTxByHash :exec
UPDATE system_pending_tx 
SET hash=?3, bump_price_count=bump_price_count+1, updated_at=?4 
WHERE chain_id=?1 AND hash=?2
`

type ReplacePendingTxByHashParams struct {
	Hash      string
	UpdatedAt sql.NullInt64
	ChainID   int64
	Hash_2    string
}

func (q *Queries) ReplacePendingTxByHash(ctx context.Context, arg ReplacePendingTxByHashParams) error {
	_, err := q.exec(ctx, q.replacePendingTxByHashStmt, replacePendingTxByHash,
		arg.Hash,
		arg.UpdatedAt,
		arg.ChainID,
		arg.Hash_2,
	)
	return err
}
