// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: registry.sql

package db

import (
	"context"
)

const getTable = `-- name: GetTable :one
SELECT id, structure, controller, prefix, created_at, chain_id FROM registry WHERE chain_id =?1 AND id = ?2
`

type GetTableParams struct {
	ChainID int64
	ID      int64
}

func (q *Queries) GetTable(ctx context.Context, arg GetTableParams) (Registry, error) {
	row := q.queryRow(ctx, q.getTableStmt, getTable, arg.ChainID, arg.ID)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Structure,
		&i.Controller,
		&i.Prefix,
		&i.CreatedAt,
		&i.ChainID,
	)
	return i, err
}
