apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-01
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: VALIDATOR_ALCHEMY_OPTIMISM_KOVAN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tableland-secret
                  key: validator-alchemy-optimism-kovan-api-key
            - name: VALIDATOR_OPTIMISM_KOVAN_SIGNER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: tableland-secret
                  key: validator-optimism-kovan-signer-private-key
