{
 "title": "Validator",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Is everything ok?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Txn confirmation retries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "attempts" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chain_id) (tableland_wallettracker_txn_confirmation_attempts{service_name=\"tableland:api\"})",
     "legendFormat": "Chain ID {{chain_id}}"
    }
   ]
  },
  {
   "title": "HealthBot - e2e check",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sum by (chain_name) (tableland_healthbot_e2eprobe_last_check{namespace=\"$namespace\"})",
     "legendFormat": "Last check {{chain_name}}"
    },
    {
     "expr": "time() - sum by (chain_name) (tableland_healthbot_e2eprobe_last_successful_check{namespace=\"$namespace\"})",
     "legendFormat": "Last success {{chain_name}}"
    }
   ]
  },
  {
   "title": "Txn Gas Price Bumps",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bumps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chain_id) (increase(tableland_wallettracker_gas_bumps{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "Chain ID {{chain_id}}"
    }
   ]
  },
  {
   "title": "Wallet balances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chain_id) (tableland_wallettracker_balance_wei{service_name=\"tableland:api\"})/1000000000000000000",
     "legendFormat": "Chain ID {{chain_id}}"
    }
   ]
  },
  {
   "title": "Ethereum node API is healthy",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chain_id)(tableland_wallettracker_eth_client_unhealthy{service_name=\"tableland:api\"}) < BOOL 1",
     "legendFormat": "ChainID: {{chain_id}}"
    }
   ]
  },
  {
   "title": "Pending txns",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "txns" } },
   "targets": [
    {
     "expr": "sum by (chain_id) (tableland_wallettracker_pending_txns{service_name=\"tableland:api\"})",
     "legendFormat": "ChainID {{chain_id}}"
    }
   ]
  },
  {
   "title": "Events processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last detected block height",
   "type": "timeseries",
   "description": "Shows the last block number detected. It should always have a positive trend.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (chain_id) (tableland_eventfeed_height{service_name=\"tableland:api\"})",
     "legendFormat": "ChainID: {{chain_id}}"
    }
   ]
  },
  {
   "title": "Last processed block height",
   "type": "timeseries",
   "description": "Show the last successfully processed event height",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by (chain_id) (tableland_eventprocessor_last_processed_height{service_name=\"tableland:api\"})",
     "legendFormat": "ChainID: {{chain_id}}"
    }
   ]
  },
  {
   "title": "Detected Event Types per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "c/s" } },
   "targets": [
    {
     "expr": "sum by (chain_id, name) (rate(tableland_eventfeed_eventypes_count{service_name=\"tableland:api\"}[5m]))",
     "legendFormat": "ChainID: {{chain_id}} Event: {{name}}"
    }
   ]
  },
  {
   "title": "Processed Event Types per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (chaind_id, eventtype) (rate(tableland_eventprocessor_event_execution_count{service_name=\"tableland:api\"}[5m]))",
     "legendFormat": "{{chain_id}} {{eventtype}}"
    }
   ]
  },
  {
   "title": "Event processing latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(tableland_eventprocessor_event_execution_latency_bucket{service_name=\"tableland:api\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block processing latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(tableland_eventprocessor_block_execution_latency_bucket{service_name=\"tableland:api\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Retry execution rounds",
   "type": "stat",
   "description": "How many times the current pending event to be processed was retried. This number should be in general zero. Maybe up to 3. If this number is high, something is wrong sine we're stuck at trying to process the event for some reason that should be fixed.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chain_id) (tableland_eventprocessor_execution_round{service_name=\"tableland:api\"})",
     "legendFormat": "ChainID {{chain_id}}"
    }
   ]
  },
  {
   "title": "Wallet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nonces",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(chain_id) (tableland_wallettracker_nonce{service_name=\"tableland:api\"})",
     "legendFormat": "ChainID {{chain_id}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status Code Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_status_code) (\n  rate(http_server_request_count{service_name=\"tableland:api\"}[10m])\n)"
    }
   ]
  },
  {
   "title": "Public APIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JSON RPC Request/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (\n  rate(tableland_mesa_call_count{service_name=\"tableland:api\"}[5m])\n)\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "JSON RPC 95-tile latency",
   "type": "timeseries",
   "description": "The latency of 95% tile. Note that CreateTable is a long running request since requires sending a txn to Ethereum. The rest should have low-ish latencies.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tableland_mesa_call_latency_bucket{service_name=\"tableland:api\"}[10m])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "REST Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum by (method) (\n  rate(tableland_system_call_count{service_name=\"tableland:api\"}[$__rate_interval])\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "REST 95-tile latency",
   "type": "timeseries",
   "description": "The latency of 95% tile. Note that CreateTable is a long running request since requires sending a txn to Ethereum. The rest should have low-ish latencies.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tableland_system_call_latency_bucket{service_name=\"tableland:api\"}[10m])) by (le, method))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SQL Store calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Method Request/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(tableland_sqlstore_call_count{service_name=\"tableland:api\"}[5m])\n)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "SQLStore 95-tile latency",
     "type": "timeseries",
     "description": "The latency of 95% tile. Note that CreateTable is a long running request since requires sending a txn to Ethereum. The rest should have low-ish latencies.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tableland_sqlstore_call_latency_bucket{service_name=\"tableland:api\"}[5m])) by (le, method))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage (runtime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_runtime_go_mem_heap_inuse",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  }
 ]
}