services:
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    volumes:
      - ${PWD}/observability/prometheus:/etc/prometheus
      - ${PWD}/${ENVIROMENT}/prometheus:/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    user: root
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.0.1
    container_name: grafana
    volumes:
      - ${PWD}/observability/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
