// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type SystemAuth struct {
	Address          string
	CreatedAt        time.Time
	LastSeen         sql.NullTime
	CreateTableCount int32
	RunSqlCount      int32
}

type SystemTable struct {
	Controller  string
	CreatedAt   time.Time
	ID          int64
	Structure   sql.NullString
	Description sql.NullString
	Name        sql.NullString
}
