// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

type Registry struct {
	CreatedAt   time.Time
	ID          pgtype.Numeric
	Structure   string
	Controller  string
	Description string
	Name        string
}

type SystemAuth struct {
	Address          string
	CreatedAt        time.Time
	LastSeen         sql.NullTime
	CreateTableCount int32
	RunSqlCount      int32
}
