// Code generated by sqlc. DO NOT EDIT.
// source: nonce.sql

package db

import (
	"context"
)

const deletePendingTxByHash = `-- name: DeletePendingTxByHash :exec
DELETE FROM system_pending_tx WHERE hash = $1
`

func (q *Queries) DeletePendingTxByHash(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deletePendingTxByHash, hash)
	return err
}

const getNonce = `-- name: GetNonce :one
SELECT network, address, nonce FROM system_nonce WHERE address = $1 AND network = $2
`

type GetNonceParams struct {
	Address string
	Network string
}

func (q *Queries) GetNonce(ctx context.Context, arg GetNonceParams) (SystemNonce, error) {
	row := q.db.QueryRow(ctx, getNonce, arg.Address, arg.Network)
	var i SystemNonce
	err := row.Scan(&i.Network, &i.Address, &i.Nonce)
	return i, err
}

const insertPendingTx = `-- name: InsertPendingTx :exec
INSERT INTO system_pending_tx ("network", "address", "hash", "nonce") VALUES ($1, $2, $3, $4)
`

type InsertPendingTxParams struct {
	Network string
	Address string
	Hash    string
	Nonce   int64
}

func (q *Queries) InsertPendingTx(ctx context.Context, arg InsertPendingTxParams) error {
	_, err := q.db.Exec(ctx, insertPendingTx,
		arg.Network,
		arg.Address,
		arg.Hash,
		arg.Nonce,
	)
	return err
}

const listPendingTx = `-- name: ListPendingTx :many
SELECT network, address, hash, nonce FROM system_pending_tx WHERE address = $1 AND network = $2
`

type ListPendingTxParams struct {
	Address string
	Network string
}

func (q *Queries) ListPendingTx(ctx context.Context, arg ListPendingTxParams) ([]SystemPendingTx, error) {
	rows, err := q.db.Query(ctx, listPendingTx, arg.Address, arg.Network)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemPendingTx
	for rows.Next() {
		var i SystemPendingTx
		if err := rows.Scan(
			&i.Network,
			&i.Address,
			&i.Hash,
			&i.Nonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNonce = `-- name: UpsertNonce :exec
INSERT INTO system_nonce ("network", "address", "nonce") VALUES ($1, $2, $3)
    ON CONFLICT (network, address)
    DO UPDATE SET nonce = $3
    WHERE system_nonce.address = $2 AND system_nonce.network = $1
`

type UpsertNonceParams struct {
	Network string
	Address string
	Nonce   int64
}

func (q *Queries) UpsertNonce(ctx context.Context, arg UpsertNonceParams) error {
	_, err := q.db.Exec(ctx, upsertNonce, arg.Network, arg.Address, arg.Nonce)
	return err
}
