// Code generated by sqlc. DO NOT EDIT.
// source: registry.sql

package db

import (
	"context"

	"github.com/jackc/pgtype"
)

const getTable = `-- name: GetTable :one
SELECT created_at, id, structure, controller, prefix, chain_id FROM registry WHERE chain_id =$1 AND id = $2
`

type GetTableParams struct {
	ChainID int64
	ID      pgtype.Numeric
}

func (q *Queries) GetTable(ctx context.Context, arg GetTableParams) (Registry, error) {
	row := q.db.QueryRow(ctx, getTable, arg.ChainID, arg.ID)
	var i Registry
	err := row.Scan(
		&i.CreatedAt,
		&i.ID,
		&i.Structure,
		&i.Controller,
		&i.Prefix,
		&i.ChainID,
	)
	return i, err
}

const getTablesByController = `-- name: GetTablesByController :many
SELECT created_at, id, structure, controller, prefix, chain_id FROM registry WHERE chain_id=$1 AND controller ILIKE $2
`

type GetTablesByControllerParams struct {
	ChainID    int64
	Controller string
}

func (q *Queries) GetTablesByController(ctx context.Context, arg GetTablesByControllerParams) ([]Registry, error) {
	rows, err := q.db.Query(ctx, getTablesByController, arg.ChainID, arg.Controller)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Registry
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.CreatedAt,
			&i.ID,
			&i.Structure,
			&i.Controller,
			&i.Prefix,
			&i.ChainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
