// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: registry.sql

package db

import (
	"context"
)

const getTable = `-- name: GetTable :one
SELECT id, structure, controller, prefix, created_at, chain_id FROM registry WHERE chain_id =?1 AND id = ?2
`

type GetTableParams struct {
	ChainID int64
	ID      int64
}

func (q *Queries) GetTable(ctx context.Context, arg GetTableParams) (Registry, error) {
	row := q.queryRow(ctx, q.getTableStmt, getTable, arg.ChainID, arg.ID)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Structure,
		&i.Controller,
		&i.Prefix,
		&i.CreatedAt,
		&i.ChainID,
	)
	return i, err
}

const getTablesByController = `-- name: GetTablesByController :many
SELECT id, structure, controller, prefix, created_at, chain_id FROM registry WHERE chain_id=?1 AND upper(controller) LIKE upper(?2)
`

type GetTablesByControllerParams struct {
	ChainID int64
	UPPER   string
}

func (q *Queries) GetTablesByController(ctx context.Context, arg GetTablesByControllerParams) ([]Registry, error) {
	rows, err := q.query(ctx, q.getTablesByControllerStmt, getTablesByController, arg.ChainID, arg.UPPER)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Registry
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.ID,
			&i.Structure,
			&i.Controller,
			&i.Prefix,
			&i.CreatedAt,
			&i.ChainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTablesByStructure = `-- name: GetTablesByStructure :many
SELECT id, structure, controller, prefix, created_at, chain_id FROM registry WHERE chain_id=?1 AND structure=?2
`

type GetTablesByStructureParams struct {
	ChainID   int64
	Structure string
}

func (q *Queries) GetTablesByStructure(ctx context.Context, arg GetTablesByStructureParams) ([]Registry, error) {
	rows, err := q.query(ctx, q.getTablesByStructureStmt, getTablesByStructure, arg.ChainID, arg.Structure)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Registry
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.ID,
			&i.Structure,
			&i.Controller,
			&i.Prefix,
			&i.CreatedAt,
			&i.ChainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
