// Code generated by sqlc. DO NOT EDIT.
// source: tables.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTable = `-- name: GetTable :one
SELECT uuid, controller, created_at FROM system_tables WHERE uuid = $1
`

func (q *Queries) GetTable(ctx context.Context, uuid uuid.UUID) (SystemTable, error) {
	row := q.db.QueryRow(ctx, getTable, uuid)
	var i SystemTable
	err := row.Scan(&i.UUID, &i.Controller, &i.CreatedAt)
	return i, err
}

const insertTable = `-- name: InsertTable :exec
INSERT INTO system_tables (
    uuid,
    controller
    ) VALUES (
      $1,
      $2)
`

type InsertTableParams struct {
	UUID       uuid.UUID
	Controller string
}

func (q *Queries) InsertTable(ctx context.Context, arg InsertTableParams) error {
	_, err := q.db.Exec(ctx, insertTable, arg.UUID, arg.Controller)
	return err
}
